### ISSUE TITLE
"RuntimeError: Could not determine platform" for Intel Edison

### ISSUE THREAD

**Issue by geotheory** [adafruit/Adafruit_Nokia_LCD#7]
I'm trying to use an [adapted script](https://communities.intel.com/thread/77015?start=0&tstart=0) to power a Nokia 5110 on an Intel Edison (Yocto Poky running on Sparkfun blocks not Arduino).  The script is basically `shapes.py` with the following configuration:

    # Edison hardware SPI config:
    #DC = 36
    #RST = 48
    #SPI_PORT = 5
    #SPI_DEVICE = 1
     
    # Edison software SPI config:
    SCLK = 10
    DIN = 11
    DC = 36
    RST = 48
    CS = 23

But it fails on line 28:
 
    >>> disp = LCD.PCD8544(DC, RST, SCLK, DIN, CS)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "build/bdist.linux-i686/egg/Adafruit_Nokia_LCD/PCD8544.py", line 60, in __init__
      File "build/bdist.linux-i686/egg/Adafruit_GPIO/GPIO.py", line 426, in get_platform_gpio
    RuntimeError: Could not determine platform.
 
Line 60 in PCD8544.py is: `self._gpio = GPIO.get_platform_gpio()`.  I [note that your library](https://github.com/adafruit/Adafruit_Python_GPIO/pull/29/files?diff=split) is supposed to use `mraa` to identify platform.  When I call `mraa.getPlatformName()` I get `'Intel Edison'`...
 
Any idea what the problem is here?

If it helps:

    root@edison:/usr/lib/python2.7# python platform.py
    Linux-3.10.17-poky-edison+-i686-with-glibc2.0

**Comment by geotheory** [comment]
OK solved. Needed to install https://github.com/nioinnovation/Adafruit_Python_GPIO
